# Generated by Django 4.2.2 on 2023-06-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Унікальна назва')),
                ('title', models.CharField(max_length=100, verbose_name='Назва серіалу')),
                ('image', models.CharField(max_length=50, verbose_name='Банер серіалу')),
            ],
        ),
    ]
