# Generated by Django 4.2.2 on 2023-06-10 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_films'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('films', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.films')),
                ('serials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.serials')),
            ],
        ),
    ]
