# Generated by Django 4.2.2 on 2023-06-10 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_allmovie_films_remove_allmovie_serials_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllMovie',
        ),
    ]
