# Generated by Django 4.2.2 on 2023-06-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_allmovie'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='actors',
            field=models.CharField(default=0, max_length=150, verbose_name='Актори'),
        ),
        migrations.AddField(
            model_name='films',
            name='country',
            field=models.CharField(default=0, max_length=50, verbose_name='Країна'),
        ),
        migrations.AddField(
            model_name='films',
            name='description',
            field=models.TextField(default=0, max_length=1000, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='films',
            name='director',
            field=models.CharField(default=0, max_length=50, verbose_name='Режисер'),
        ),
        migrations.AddField(
            model_name='films',
            name='duration',
            field=models.CharField(default=0, max_length=100, verbose_name='Тривалість'),
        ),
        migrations.AddField(
            model_name='films',
            name='genre',
            field=models.CharField(default=0, max_length=100, verbose_name='Жанр'),
        ),
        migrations.AddField(
            model_name='films',
            name='release_year',
            field=models.IntegerField(default=0, verbose_name='Рік виходу'),
        ),
        migrations.AddField(
            model_name='films',
            name='title_eng',
            field=models.CharField(default=0, max_length=100, verbose_name='Англійська назва фільму'),
        ),
        migrations.AddField(
            model_name='films',
            name='video',
            field=models.CharField(default=0, max_length=50, verbose_name='Шлях до фільму'),
        ),
        migrations.AddField(
            model_name='films',
            name='voicing',
            field=models.CharField(default=0, max_length=100, verbose_name='Озвучення'),
        ),
    ]
