# Generated by Django 4.2.2 on 2023-06-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_films_actors_films_country_films_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='video',
            field=models.CharField(default=0, max_length=200, verbose_name='Шлях до фільму'),
        ),
    ]
