# Generated by Django 4.2.2 on 2023-06-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_my_choices_serials_actors_serials_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_choices',
            name='title',
            field=models.CharField(default=0, max_length=100, verbose_name='Назва серіалу'),
        ),
    ]
