# Generated by Django 4.2.2 on 2023-06-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_my_choices_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_choices',
            name='choice',
            field=models.CharField(max_length=154, unique=True),
        ),
    ]
