# Generated by Django 4.2.2 on 2023-06-12 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_my_choices_choice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MY_CHOICES',
            new_name='My',
        ),
    ]
