# Generated by Django 4.2.2 on 2023-06-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_films_type_serials_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='serialseason',
            name='description',
            field=models.TextField(default=0, max_length=2000, verbose_name='Посилання'),
        ),
    ]
