# Generated by Django 4.2.2 on 2023-06-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_rename_description_serialseason_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serialseason',
            old_name='title',
            new_name='title_season',
        ),
        migrations.AddField(
            model_name='serialseason',
            name='title_season_eng',
            field=models.CharField(default=0, max_length=50, verbose_name='Англ. назва сезону'),
        ),
    ]
