# Generated by Django 4.2.2 on 2023-06-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_rename_title_serialseason_title_season_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serials',
            name='description',
        ),
        migrations.RemoveField(
            model_name='serials',
            name='release_year',
        ),
        migrations.RemoveField(
            model_name='serials',
            name='title_season',
        ),
        migrations.RemoveField(
            model_name='serials',
            name='title_season_eng',
        ),
        migrations.AddField(
            model_name='serialseason',
            name='description',
            field=models.TextField(default=0, max_length=1500, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='serialseason',
            name='release_year',
            field=models.IntegerField(default=0, verbose_name='Рік виходу'),
        ),
    ]
