# Generated by Django 4.2.2 on 2023-07-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_serialseason_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Унікальна назва')),
                ('title', models.CharField(max_length=100, verbose_name='Назва новини')),
                ('image', models.CharField(max_length=50, verbose_name='Банер новини')),
            ],
        ),
    ]
